python_file: "/home/ksharma2/dist-geo-schelling/run_distributed.py"
shapefile: "/home/ksharma2/dist-geo-schelling/shapefiles/CA/CA.shp"
data_path: "/home/ksharma2/jobs/results/dist-geo-schelling/all_partitions/"
demography_ratio: 0.71
similarity_threshold: 0.4
number_of_iterations: 50
python_path: python
number_of_processes: 8
spacing: 0.009
empty_ratio: 0.1
