python_file: "/home/ksharma2/dist-geo-schelling/run_single.py"
shapefile: "/home/ksharma2/dist-geo-schelling/shapefiles/CA/CA.shp"
data_path: "/home/ksharma2/jobs/results/dist-geo-schelling/single/"
empty_ratio: 0.1
demography_ratio: 0.71
similarity_threshold: 0.4
number_of_iterations: 50
python_path: python
